services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./init/init.sql:/docker-entrypoint-init.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: db_comment
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql123
      MYSQL_ROOT_PASSWORD: mysql123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    ports:
      - 3001:3001
    expose:
      - 3000
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: nodeappservice
      PORT: 3001
      DB_PORT: 3306
      DB_NAME: db_comment
      DB_USER: 'mysql'
      DB_HOST: 'mysqldb'
      DB_PASSWORD: 'mysql123'
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge